Question 1
===

In this question, we consider the marketing.csv data which contains 200 observations and 4 variables. The response variable is sales, denoted as $y$. The explanatory variables — measured in thousands of dollars — are advertising budget spent on youtube, newspapers and facebook, respectively, which are denoted as $X1$, $X2$ and $X3$, respectively. 

To model impacts of the media strategies on logarithm of sales, a researcher uses the following multiple linear regression:

$\begin{equation} \tag{1}
Y = log(y) = \beta_0 + \beta_1 log(X_1) + \beta_2 log(X_2) + \beta_3 log(X_3) + \epsilon,
\end{equation}$
$\begin{equation} \tag{2}
 = \mathbf{X}\mathbf{\beta} + \epsilon
\end{equation}$

where $Y, log(X1), log(X2) and log(X3)$ is a vector of $n × 1$ ($n$ is the number of observations in the dataset), $\mathbf{X}$ = $(1_n, log(X1), log(X2), log(X3))$ and $\mathbf{\beta}$ = $[\beta_0, \beta_1, \beta_2, \beta_3]'$.

The parameter $\beta$ in Equation (2) can be estimated by minimising the following loss function - mean squared errors:
$\begin{equation} \tag{3}
\mathcal{L} = \frac{1}{n} (Y - \mathbf{X\beta})'(Y - \mathbf{X\beta}) = \frac{1}{n} \sum_{i=1}^{n} (Y_i - \mathbf{X_i\beta})^2
\end{equation}$

It is well-known that the optimal solution of $\beta$ in Equation (3), denoted as $\hat{\beta}$, has the following form:
$\begin{equation} \tag{4}
\hat{\beta} = (\mathbf{X}'\mathbf{X})^{-1}\mathbf{X}'Y
\end{equation}$

and its standard deviation is
$\begin{equation} \tag{5}
s.e(\hat{\beta}) = \sqrt{s^2(\mathbf{X}'\mathbf{X})^{-1}} \ where \ s^2 = \frac{1}{n - 4} \sum_{i=1}^{n} (Y_i - \mathbf{X_i\hat{\beta}})^2, i = 1,2,...,n
\end{equation}$

### a.
Use equations (4) and (5) to estimate $\beta$ and its standard deviation in Python. Comment on impacts of the media advertisement on sales.

In [24]:
import numpy as np
import pandas as pd

data = pd.read_csv("marketing.csv", sep=",")
# Remove rows where there is a 0 as this results in errors when trying to take the log
zeroIdxs = np.where((data["youtube"] == 0) | (data["newspaper"] == 0) | (data["facebook"] == 0))
for idx in zeroIdxs[0]:
    data.drop(index = idx, inplace = True)
data.reset_index(drop = True, inplace = True)

XMat = np.transpose(np.matrix([np.ones(n), np.log10(data["youtube"]), np.log10(data["newspaper"]), np.log10(data["facebook"])]))
YMat = np.transpose(np.matrix(data["sales"]))
betahat = (1 / (np.transpose(XMat) * XMat)) * (np.transpose(XMat) * YMat)
temp = 0
for i in range(len(data)):
    temp += np.power((YMat[i] - XMat[i] * betahat), 2)
stddev = np.sqrt(((1 / (n - 4)) * temp).item() * (1 / (np.transpose(XMat) * XMat)))

print('\u03B2: ', end="")
print(betahat)
print('\u03C3: ', end="")
print(stddev)

β: [[69.80318991]
 [32.71307425]
 [48.0206547 ]
 [52.17758438]]
σ: [[18.59239351 12.80300594 15.61952352 16.3378405 ]
 [12.80300594  8.63330818 10.73885012 11.24132574]
 [15.61952352 10.73885012 12.57692932 13.60539802]
 [16.3378405  11.24132574 13.60539802 13.57527735]]


### b.
Write down a step-by-step procedure of Classical Gradient Descent to estimate $\beta$ in Equation (3)

1. Choose arbitrary starting point $x^k, k = 0$.
2. Decide learning rate ($\alpha$).
3. Find the gradient $\mathcal{L}$. $\nabla f(x^k) = [\frac{\partial f}{\partial \beta_0}, \frac{\partial f}{\partial \beta_1}, \frac{\partial f}{\partial \beta_2}, \frac{\partial f}{\partial \beta_3}]'$
4. Update $x^{k+1},\ x^{k+1} = x^k - \alpha \nabla f (x^k)$
5. Repeat steps 2 - 4 until stopping criteria is met. This is usually of the form $x^{k+1} - x^k < \epsilon = 1e-6$
6. Obtain result. Note: This is usually a local minimum.

c.
===
Write Python code to implement the Classical Gradient Descent procedure provided in (b).

d.
===
 Discuss the results obtained from (c) and compare it with that obtained from (a).